# -*- coding: utf-8 -*-
"""w3 groq for cloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122zuDSquYAr5sSQr393eBR4oMqQEsxhl
"""

# Install the necessary libraries
#!pip install -q groq gradio

import os
from groq import Groq

client = Groq()

# Define the core AI function
def chat_with_groq(user_input):
    completion = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[
            {"role": "system", "content": "You are a concise and professional AI Assistant."},
            {"role": "user", "content": user_input}
        ]
    )
    return completion.choices[0].message.content

import gradio as gr

# Create and launch the UI
demo = gr.Interface(
    fn=chat_with_groq,
    inputs=gr.Textbox(label="Enter your prompt", lines=5),
    outputs=gr.Textbox(label="AI Response", lines=5),
    title="⚡ Instant AI Prototyper"
)

# Launch the interface
demo.launch(debug=True)

